Hypervisor_Provider : ""
minishift_PATH : ""
minishift_lib_MODULE : ""
iso_url : ""
openshift_USER : ""
openshift_PASSWORD : ""
RHN_USERNAME : ""
RHN_PASSWORD : ""

#Set if tested binary is upstream minishift or downstream cdk (yes/no, y/n, true/false)
Is_Downstream :
#Set the project inputs (python project name, python registry path and python service name). It uses image from redhat registry.
openshift_python_PROJECT : "test-python27"
openshift_python_REGISTRY : "registry.access.redhat.com/rhscl/python-27-rhel7~https://github.com/openshift/django-ex" 
service_python_NAME : "django-ex"
#Set the project inputs (ruby project name, ruby registry path and ruby service name). It uses image from docker registry.
openshift_ruby_PROJECT : "test-ruby"
openshift_ruby_REGISTRY : "openshift/ruby-20-centos7~https://github.com/openshift/ruby-hello-world" 
service_ruby_NAME : "ruby-hello-world"
#Set the project inputs (perl project name, perl registry path and perl service name). It uses image from redhat registry.
openshift_perl_PROJECT : "test-perl"
openshift_perl_REGISTRY : "registry.access.redhat.com/rhscl/perl-520-rhel7~https://github.com/openshift/dancer-ex" 
service_perl_NAME : "dancer-ex"
#Set the project inputs (nodejs project name, nodejs registry path and nodejs service name). It uses image from redhat registry.
openshift_nodejs_PROJECT : "test-nodejs"
openshift_nodejs_REGISTRY : "registry.access.redhat.com/rhscl/nodejs-4-rhel7~https://github.com/openshift/nodejs-ex" 
service_nodejs_NAME : "nodejs-ex"
#Set the project inputs (php project name, template name and php service name). It uses the template provided by openshift.
openshift_php_PROJECT : "test-php"
openshift_php_template : "cakephp-mysql-example" 
service_php_NAME : "cakephp-mysql-example"
#Set the project inputs (phpnodejs+mongodb project name, template name and php service name). It uses the template provided by openshift.
openshift_nodejsmongodb_PROJECT : "test-nodejs-mongodb"
openshift_nodejsmongodb_TEMPLATE : "nodejs-mongodb-example" 
service_nodejsmongodb_NAME : "nodejs-mongodb-example"
